CREATE TABLE patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          email VARCHAR(150) NOT NULL UNIQUE,
                          phone_number VARCHAR(50) NOT NULL
);

CREATE TABLE doctors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL,
                         specialisation VARCHAR(100) NOT NULL
);

CREATE TABLE appointments (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              patient_id BIGINT NOT NULL,
                              doctor_id BIGINT NOT NULL,
                              appointment_date VARCHAR(100) NOT NULL,
                              status VARCHAR(50) NOT NULL,

                              CONSTRAINT fk_appointment_patient
                                  FOREIGN KEY (patient_id)
                                      REFERENCES patients(id),

                              CONSTRAINT fk_appointment_doctor
                                  FOREIGN KEY (doctor_id)
                                      REFERENCES doctors(id)
);